services:
  - type: web
    name: agrisahayak-ai-service
    env: python
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: agrisahayak-backend-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
